version: '3.8'

services:
  # PostgreSQL Database for Development
  postgres:
    image: postgres:15-alpine
    container_name: finance_tracker_db_dev
    environment:
      POSTGRES_DB: finance_tracker_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    networks:
      - finance_network_dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Finance Tracker Backend API (Development)
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: finance_tracker_api_dev
    environment:
      NODE_ENV: development
      PORT: 5000
      DATABASE_URL: postgresql://postgres:postgres_password@postgres:5432/finance_tracker_dev
      JWT_SECRET: dev-jwt-secret-key-for-development-only
      JWT_REFRESH_SECRET: dev-refresh-secret-key-for-development-only
      JWT_EXPIRES_IN: 7d
      JWT_REFRESH_EXPIRES_IN: 30d
      CORS_ORIGIN: http://localhost:5173
      RATE_LIMIT_WINDOW_MS: 900000
      RATE_LIMIT_MAX_REQUESTS: 100
      LOG_LEVEL: debug
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - finance_network_dev
    restart: unless-stopped

volumes:
  postgres_dev_data:
    driver: local

networks:
  finance_network_dev:
    driver: bridge 